# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4531072802e96d24a4d89f77ee1cfe2d2d48d84860b35ef23f029e4eb62f592155aac7ef102f140c2241c2769875d474061cd43887daf02ccd54a8c1c998d1f5

test:
  secret_key_base: 3aa16894ac45c086a070031e6c0690bdcfa3aed8f43fca3e9684d56e709c244abeaafd5612645e98d31dc00969c61755c7ab45d3e8cc08ccc510a007e11225d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
